bool IsEqualStrings(char* a, char* b);
bool IsEqualStringsFragment(char* a, char* b, int ceillingB);
int StringLength(char* str);
long long StringToInt(char* str);
long long StringToInt(char* str, int start, int end);
char* CopyString(char* str, int start, int end);
long long TranslateTime(int days, char* month, int year, int hours, int minutes, int seconds);
int FindSymbol(char* str, int start, char symbol);
long Partition(long** arr, long l, long r);
void QuickSort(long** arr, long l, long r, long length, long n);